# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink: pretty

# Setup
title:            Fran Exposito
tagline:          'Blog'
description:      'This is a theme for Jekyll, do it with love'
url:              http://franexposito.es
baseurl:          /

author:
  name:           'Fran Exposito'
  url:            https://twitter.com/FranExp

paginate:         5

# Custom vars
version:          1.0

# Social vars
active : yes # yes = active, empty = deactive
github: http://github.com/franexposito
linkedin:
twitter: http://twitter.com/FranExp
facebook:
instagram:
