# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title:            Fran Exposito
tagline:          'Blog'
description:      'This is a theme for Jekyll, do it with love'
url:              http://franexposito.es
baseurl:          /
gems:
  - jekyll-sitemap

author:
  name:           'Fran Exposito'
  url:            https://twitter.com/FranExp

paginate:         5

# Custom vars
version:          1.0         

# Social vars
active : yes # yes = active, empty = deactive
github: http://github.com/franexposito
linkedin: http://linkdin.com
twitter: http://twitter.com/FranExp
facebook: http://facebook.com
instagram: http://instagram.com
