# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title:            Fran Exposito
tagline:          'Blog'
description:      ''
url:              http://franexposito.es
baseurl:          /
gems:
  - jekyll-sitemap

author:
  name:           'Fran Exposito'
  url:            https://twitter.com/FranExp

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
